apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    name: nginx
    image: nginx
    env:
      - name: course
        values: devops
      - name: trainer
        value: sivakumar
      - name: duration
        value: "120hrs"
       