apiVersion: v1
kind: Pod  
metadata:
  name: expenses
  labels:
    project: expenses
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx 
    - name: almalinux
      image: almalinux:9
      command: ["sleep","100"]