apiVersion: v1
kind: Pod  
metadata:
  name: expense
  labels:
    project: expense
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx 
    - name: almalinux
      image: almalinux:9